### ISSUE TITLE
Components of 禸

### ISSUE THREAD

**Issue by ospalh** [KanjiVG/kanjivg#83] opened 2014-07-27 09:58 UTC
禸 and all kanji that use it: missing component information for ム and 冂?

**Comment by benkasminbullock** [comment] 2022-03-25 00:18
I was able to confirm that there are some elements with missing component information. For example, [kanji/09f72.svg
](https://github.com/KanjiVG/kanjivg/blob/master/kanji/09f72.svg) is missing the 冂 component, which should be inserted around lines 87 and 88. The issue is complicated by the fact that 禸 is used as a kind of generic catch-all for a variety of constructions.

**Comment by benkasminbullock** [comment] 2022-03-30 23:56
This issue should be fixed by the following commits:

https://github.com/KanjiVG/kanjivg/tree/split-079b8

Can you check it and see if that does the job? If I don't hear anything, I'll go ahead and merge that.

**Closed** 2022-03-31 21:00 UTC
Labels: Please check
