### ISSUE TITLE
衆

### ISSUE THREAD

**Issue by bradleycowan** [KanjiVG/kanjivg#153] opened 2017-02-27 11:17 UTC
After stoke 6, strokes 9 and 10 should come next, then 7, 8, 11, 12

**Comment by ospalh** [comment] 2017-02-27 13:44
I suspect the situation here is similar to the one at #154.
You mean of the six bottom strokes, the two central ones should come first, then the two left one, and then the two right ones?
Like [this](https://github.com/KanjiVG/kanjivg/blob/master/kanji/08846.svg)?

**Comment by bradleycowan** [comment] 2017-02-27 15:23
Again it must've been the app and tagaini.net that's displaying wrongly. Was unaware that it had been amended. Thanks for getting in touch!

**Comment by ospalh** [comment] 2017-02-27 15:27
I’ll call it a duplicate of #148 then.

**Closed by ospalh** 2017-02-27 15:27 UTC
