### ISSUE TITLE
慳 left hand radical is wrong

### ISSUE THREAD

**Issue by benkasminbullock** [KanjiVG/kanjivg#181] opened 2019-03-11 07:15 UTC
The left "heart" radical of 慳 is written in the wrong order.

http://kanjivg.tagaini.net/viewer.html?kanji=%E6%85%B3

**Comment by wareya** [comment] 2019-03-11 07:16
The order in KanjiVG's actual current data is different:

https://github.com/KanjiVG/kanjivg/blob/master/kanji/06173.svg

The viewer should probably be taken offline entirely if nobody is going to update its data.

**Comment by ospalh** [comment] 2019-03-11 12:23
Thanks, @wareya, you’re right.
Yeah, at least the viewer should be delinked from the top description.
Anyway, i’ll call this another duplicate of issue #148.

**Closed by ospalh** 2019-03-11 12:23 UTC

**Comment by Gnurou** [comment] 2019-03-11 14:37
Finally updated the viewer to use the final data. My deepest apologies for not doing this earlier. >_<
