### ISSUE TITLE
Errors in groups

### ISSUE THREAD

**Issue by siikamiika** [KanjiVG/kanjivg#128] opened 2016-03-24 16:16 UTC
Opening this to keep a track on the erros I've found in the groups and to ask some questions about them before fixing them.

珍: see #127

満: Should 両 be inside 廿? Doesnt seem logical, but is there some etymological reason for this? What does `kvg:phon` mean? It says "TBD" at http://kanjivg.tagaini.net/format.html.

叟: 丨 is misplaced. Probably also affects 搜, 嫂, 艘, 溲. 

蔵: 臣 shouldn't be inside 戈. Same with 蔵.

兆: I don't think 冫 should be inside 儿. 兆 is used in 逃, 挑, 跳, 眺, 桃, 銚, 姚, 窕, 佻, 晁, 誂.

That's all so far. I'll add more if I find any. Please point out any mistakes I've made.

**Comment by benkasminbullock** [comment] 2021-04-18 04:32
> Opening this to keep a track on the erros I've found in the groups and to ask some questions about them before fixing them.
> 
> 珍: see #127
> 
> 満: Should 両 be inside 廿? Doesnt seem logical, but is there some etymological reason for this? What does `kvg:phon` mean? It says "TBD" at http://kanjivg.tagaini.net/format.html.

I couldn't work it out either. It's possible the person who wrote that file doesn't know either. The KanjiVG data was originally created by Ulrich Apel but then the maintainer of the files is another person.
 
> 叟: 丨 is misplaced. Probably also affects 搜, 嫂, 艘, 溲.

Why do you think so:

![memory](https://user-images.githubusercontent.com/102005/115134230-496eff80-a049-11eb-9b5c-ba9505452eb1.png)

> 蔵: 臣 shouldn't be inside 戈. Same with 蔵.

I'm not sure if it is really, the 戈 seems to be shorthand for the bottom element in total.

> 兆: I don't think 冫 should be inside 儿. 兆 is used in 逃, 挑, 跳, 眺, 桃, 銚, 姚, 窕, 佻, 晁, 誂.

This is confirmed, someone probably forgot to close the `<g>` tag.

> That's all so far. I'll add more if I find any. Please point out any mistakes I've made.

**Comment by benkasminbullock** [comment] 2022-03-31 21:15
> 満: Should 両 be inside 廿? Doesnt seem logical, but is there some etymological reason for this? 

I'm not sure why that was used. The basic problem here is that there is no `kvg:element` that can be used for the right side of 満. We can either invent our own thing or, for example, use a decomposition like ⿱艹両, which I think is a good solution since it makes KanjiVG compatible with [IDS](https://github.com/cjkvi/cjkvi-ids). It would also make sense to add a group for  艹 and remove the 十 group, in my opinion.

> What does kvg:phon mean? It says "TBD" at http://kanjivg.tagaini.net/format.html.

I've added information on kvg:phon to the page, which I copy-pasted from Ulrich Apel's post to the kanjivg mailing list. Here is a link:

https://kanjivg.tagaini.net/format.html#phon

**Comment by benkasminbullock** [comment] 2022-04-06 03:49
> 兆: I don't think 冫 should be inside 儿. 兆 is used in 逃, 挑, 跳, 眺, 桃, 銚, 姚, 窕, 佻, 晁, 誂.

This should be fixed by the above commit. There was also another error where the wrong groups had been applied to the "MidFst" variants so that the 儿 had been applied to the first and fourth strokes, where it should have been applied to the first and second strokes.

> That's all so far. I'll add more if I find any. 

Please can you open a separate issue for each problem you find. Then we can see how much progress is being made as the issues can be closed. If you add lots of different and disparate things to one issue, it never gets closed, the discussion becomes too long to comfortably read, and people get confused. So please use one issue per one problem. Thanks!

**Comment by benkasminbullock** [comment] 2022-04-06 12:12
> 叟: 丨 is misplaced. Probably also affects 搜, 嫂, 艘, 溲.

There were four instances where this was mis-ordered, most of them were actually correct.

Assuming there are no setbacks, I'll close this issue after merging the two current pull requests.

**Comment by benkasminbullock** [comment] 2022-04-06 12:29
> 満: Should 両 be inside 廿? Doesnt seem logical, but is there some etymological reason for this?

This particular muddle-up is KanjiVG's way of trying to show that the top stroke of 両 is also the bottom stroke of 廿. I cannot see the point of this at all myself.

**Comment by benkasminbullock** [comment] 2022-04-07 08:54
I'll close this now. Thanks for the bug report. Please reopen this issue if you are not satisfied, or start a new issue if you notice anything else. Thanks again.

**Closed by benkasminbullock** 2022-04-07 08:54 UTC
Labels: Grouping
