### ISSUE TITLE
Wrong stroke order for 瓶 

### ISSUE THREAD

**Issue by nortonch** [KanjiVG/kanjivg#152] opened 2017-02-08 14:37 UTC
The stroke order of the right should be the same as in 瓦.  The 11th stroke should be 9th.

**Comment by vitaliylag** [comment] 2017-10-11 21:52
Even in version of 2015 year I have the same order in these two kanji. Try to update your version or check the order again.

**Comment by ospalh** [comment] 2017-10-12 07:23
Also a duplicate of #7, possibly #148.

**Closed by ospalh** 2017-10-12 07:23 UTC
